name: Main
on: [push, pull_request]

jobs:
  norminette:
    name: Norminette
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
  build:
      name: Build
      needs: norminette
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: src
      steps:
        - uses: actions/checkout@v2
        - name: make
          run: make
