name: norminette
on: [push, pull_request]

jobs:

  norminette_v3_job:
    runs-on: ubuntu-latest
    name: norminette v3
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
c1r3p4% cat build.yml 
name: build

on:
  push:
    branches:
    - main
jobs:
   build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libft v1.0
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make
